### ISSUE TITLE
Document Container Usage in README

### ISSUE THREAD

**Issue by shashankhs11** [UBC-MDS/522-wine-quality-32#22]
## Description
Update the README to include clear instructions for building, using, and updating the container image.

## Tasks

- [x] Add steps for building and running the container locally.
- [x] Include details on updating dependencies and the container image.
- [x] Document how to use Docker Compose in the README.
