### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by shashankhs11** [UBC-MDS/522-wine-quality-32#37]
## **Description**
Feedback received from Milestone 1

---

##  **Tasks**

- [x] #79
- [x] #42
- [x] #43
- [x] #81
- [ ] Does not clearly report the major findings.
- [ ] Do not present results as raw code output.
- [ ] There are references at the end of the report, but they are not referred to in the narrative.
- [x] #83
