### ISSUE TITLE
Milestone 4 - Task 1: Creating a makefile

### ISSUE THREAD

**Issue by shashankhs11** [UBC-MDS/522-wine-quality-32#45]
## **Description**
To create a makefile - this script should run the others in sequence, hard coding in the appropriate arguments. This script should:

---

##  **Tasks**

- [ ] live in the project’s root directory and be named Makefile
- [ ] be well documented (using the project README and comments inside the Makefile to explain what it does and how to use it)
- [ ] have an all target so that you can easily run the entire analysis from top to bottom by running make all at the command line
- [ ] have a clean target so that you can easily “undo” your analysis by running make clean at the command line (e.g., deletes all generate data and files).
