### ISSUE TITLE
Milestone 4 - Task 2: Writing tests and documentation for functions in scripts

### ISSUE THREAD

**Issue by shashankhs11** [UBC-MDS/522-wine-quality-32#46]
## **Description**
Write tests and documentation for functions in each script. Please make sure to implement these points referenced directly from Milestone 4 specification. We are required to follow the [workflow for writing functions and tests for data science](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/140-intro-to-testing-code.html#workflow-for-writing-functions-and-tests-for-data-science)

> You will import (in the case of Python) or source (in the case of R) these functions in your scripts to use them in your analysis. Tests will live in a test directory, with files/subdirectories organized as per the testing framework you are using. If you are using Python, we expect you to use the [pytest](https://docs.pytest.org/en/7.0.x/) Python package framework.

---

##  **Tasks for each script**

- [x] writing thorough function specifications & documentation
- [x] writing robust unit tests for these functions to ensure they work as expected
- [x] writing the code that makes up the function body

## **Splitting the scripts among the group**
- [ ] [data_download.py](https://github.com/UBC-MDS/522-wine-quality-32/blob/d8f5ead445bb17607336253c1472618e22a0c130/src/data_download.py) @Nonso-M 
- [x] #59
- [ ] [plots.py](https://github.com/UBC-MDS/522-wine-quality-32/blob/d8f5ead445bb17607336253c1472618e22a0c130/src/plots.py) @Xccci 
- [x] #54
