### ISSUE TITLE
Data Set Description

### ISSUE THREAD

**Issue by Nonso-M** [UBC-MDS/522-wine-quality-32#77]
## **Description**
As per peer review, we are elaborating more on the data set, both the Target Variable and the features

---

##  **Tasks**

- [ ] Task 1: Describe the Variables in the Dataset
- [ ] Task 2: Describe the TARGET and what each level means
- [ ] Task 3: Move the reference.bib file to the report folder
- [ ] Task 4: Add documentation at the top of each script, reordered the import and removing unused imports
